ФП10
TimurBonet/java-filmorate pull request #2
Opened 2024-01-20 16:04 UTC by TimurBonet

2024-01-21 16:56 UTC, Fleaman777 requested changes

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                "продолжительность фильма должна быть положительной.", e.getMessage());
такой подробный лог хорошо, но в нем содержится информация, которая может легко поменяться: длина описания, дата релиза, что в теории может вызвать путаницу, если такую информацию добавлять в лог, то лучше через переменную, которая отвечает за эти значения, что бы информация всегда была актуальна

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return inMemoryFilmStorage.findAll();
более грамотный подход. когда контроллер зависит только от классов сервисов, которые в свою очередь уже имеют зависимость на сторедж классы, 
так у нас каждый слой (контроллер, сервис, сторедж) будет отвечать за свою часть логики и не делать работу других уровней 

те вместо inMemoryFilmStorage.findAll() должно быть обращение к сервису с подобным методом 

аналогично в других местах

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      }
можно явно не указывать конструктор (и аннотацию @Autowire над ним), что бы внедрить компоненты. 
Достаточно повесить аннотацию @RequiredArgыConstructor над классом и сделать поля final, 

так будет меньше бойлер плейт кода, а значит улучшится восприятие

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likesList = new HashSet<>();
likesList - это же set, а из названия может показаться, что список, что может ввести в заблуждение 
можно просто оставить likes

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
аналогично с конструктором

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = inMemoryFilmStorage.findFilmById(filmId);
Film film - почему бы эту локальную переменную не сделать до if условия, что бы не дублировать получение этого значения из inMemoryFilmStorage, а использовать film переменную

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User anitherUser = inMemoryUserStorage.findUserById(otherId);
что за слово такое anither

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
отличный foreach что бы сделать его в стриме,
аналогично со следующими

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private Integer addId() {
private методы должны идти после публичных, так при беглом просмотре класса, можно будет быстро понять, какой функционал он отдает наружу

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film createFilm(Film film) throws InvalidFilmDataException, FilmAlreadyExistException {
throws InvalidFilmDataException, FilmAlreadyExistException - можно не указыыать, так как это Runtime исключения, меньше кода, лучше восприятие

аналогично в других местах

2024-01-21 16:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        for (User u : users.values()) {
можно использовать стрим

2024-01-22 03:37 UTC, TimurBonet commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User anitherUser = inMemoryUserStorage.findUserById(otherId);
Опечатка)

2024-01-22 08:49 UTC, Fleaman777 approved these changes

2024-01-22 08:49 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                "дата релиза — не раньше " + minReleaseDate + ";\n" +
отлично. то, что нужно

2024-01-22 08:49 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
все правильно, так и надо

2024-05-30 14:44 UTC, Fleaman777 approved these changes

2024-06-19 06:43 UTC, merged