ФП 12 Add database
TimurBonet/java-filmorate pull request #4
Opened 2024-06-19 15:34 UTC by TimurBonet

2024-06-20 17:57 UTC, Fleaman777 requested changes

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        log.info("Получен список всех жанров: {}", genresList.size());
я бы оставил какой-нибудь один лог, а то так получается, что логов больше чем самого кода в методе, что немного ухудшает восприятие

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User user1 = userService.getUserById(id);
почему user1 ?

аналагично в др местах

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Получен пользователь : {}", user1);
в теории, может возникнуть секьюрити ошибка, связанная с выводом в лог той информации, которая не должна там быть, если в объект User добавятся какие-нибудь сенсетив поля, поля которые содержат персональную информацию, которыми будет небезопасно делиться

что бы этого избежать, можно в лог выводить только часть несекьюрной информаци

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void addFriend(@PathVariable("id") Integer id, @PathVariable("friend_id") Integer friendId) {
а почему бы не сделать тип int ?
в случае с Integer, дальше в сирвисе может оказзаться null, что может привести к NPE 

аналогично в др местах

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping("/{id}/friends/{friend_id}")
если использовать просто friendId, то значние в аннотации PathVariable можно не добавлять

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    private void isExist(Integer filmId, Integer userId) {
хорошее вынесение общей логики в отдельный метод

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreServiceImpl.java
> +    private final GenreDAO genreDAO;
а почему что-то Storage, а что-то DAO 

если есть какая принципиальная ращница, то можно оставить как есть, 
если нет, то хорошо придерживаться одного подхода к именованию

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +        log.info(getFriendList(friendId).toString());
тоже много логов.  
и ради лога ходить в бд, не очень хорошо, тк это дополнительно нагружает приложение

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +        }
можно было бы как-то объеденить ifы 
или убрать 1й

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +        User user1 = userStorage.findUserById(id1);
сразу после попытки поулчить user1 можно проверить на null и если что викинуть исключение, 
так нам не нужно будет идти лишний раз в бд, в случае если user1 нет

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                "GROUP by F.FILM_ID";
что бы запросы чуть лучше воспринимались, можно придерживаться стиля когда ключевые слова типа SELECT, FROM и пр были в верхнем регистре, а названия полей, таблиц в нижнем

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        jdbcTemplate.batchUpdate(sqlQuery, new BatchPreparedStatementSetter() {
отлично! молодец, хорошее и правильное использование batchUpdate, а не просто обновление фильмов через foreach

2024-06-20 17:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/MpaDAOImpl.java
> +public class MpaDAOImpl implements MpaDAO {
хорошо, правильно сделал, что у каждой сущности свой сторедж класс - принцип разделения ответсвтенности работает

2024-06-21 05:59 UTC, TimurBonet commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping("/{id}/friends/{friend_id}")
Если убрать аннотацию то тесты не проходит, столкнулся здесь с таким моментом, что пройден был старый тест, а новый в этом месте рушился. Оказалось, что в старом было "friendid", а здесь "friend_Id" в запросе, поставил аннотацию именно на такой случай

2024-06-22 16:25 UTC, Fleaman777 approved these changes

2024-11-23 11:58 UTC, merged